
development:    
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  encoding: utf8
  host: localhost
  pool: 5
  username: postgres
  password: flytry88

test: &test
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  encoding: utf8
  host: localhost
  pool: 5
  username: postgres
  password: flytry88

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production
  encoding: utf8
  host: localhost
  pool: 5
  username: postgres
  password: flytry88



cucumber:
  <<: *test